spring:
  datasource:
# H2 DB용 설정
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
# maria DB용 설정
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/flowdb
#    username: flowuser
#    password: flowpassword
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
logging:
  thymeleaf:
    cache: false
  level:
    org.hibernate.type: trace